resources:
  - deployment.yml
  - service.yml
  - ingress.yml

namespace: default

commonLabels:
    app: restate

secretGenerator:
- name: restate-basic-auth
  behavior: create
  options:
    disableNameSuffixHash: true
  files:
    - auth=config/htpasswd
